version: '3.7'

services:

  elasticsearch:
    build: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    environment:
      - "cluster.name=elasticsearch"
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "XPACK_SECURITY_ENABLED=false"
    healthcheck:
      test: "curl http://elasticsearch:9200"
      interval: "1s"
      timeout: "3s"
      retries: 60

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=123qwe
      - POSTGRES_USER=postgres
      - POSTGRES_DB=movies
    ports:
      - "5432:5432"


  script:
    build: .
    volumes:
      - .:/app
    restart: always
    depends_on:
      - db

volumes:
  postgres_data:
  script:
