version: '3'

services:
  elasticsearch:
    build: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    environment:
      - "cluster.name=elasticsearch"
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "XPACK_SECURITY_ENABLED=false"
    networks:
      - elk
    healthcheck:
      test: "curl http://elasticsearch:9200"
      interval: "1s"
      timeout: "3s"
      retries: 60

  script:
    build: ./etl
    volumes:
      - ./etl:/app
    restart: always
    networks:
      - elk
    depends_on:
      - elasticsearch
  web:
    build: ./web
    volumes:
      - ./web:/app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - "DOCKER_MACHINE_IP=${DOCKER_MACHINE_IP}"
    networks:
      - elk
    depends_on:
      - elasticsearch
networks:
  elk:
    driver: bridge
