<<<<<<< HEAD:Django_flask_project/django_docker_nginx/django_movies/movies/migrations/0001_initial.py
# Generated by Django 3.1 on 2021-03-31 11:50

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
=======
# Generated by Django 3.1.7 on 2021-03-26 09:59

from django.db import migrations, models
>>>>>>> master:django_admin/django_movies/movies/migrations/0001_initial.py
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'actor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
<<<<<<< HEAD:Django_flask_project/django_docker_nginx/django_movies/movies/migrations/0001_initial.py
                ('id', models.CharField(default=uuid.UUID('668cbae9-ae2e-4725-891f-f50ec4e00398'), max_length=36, primary_key=True, serialize=False)),
=======
                ('id', models.CharField(default=uuid.UUID('f64d84c2-0afe-4b4b-ac3e-437e32f325cd'), max_length=36, primary_key=True, serialize=False)),
>>>>>>> master:django_admin/django_movies/movies/migrations/0001_initial.py
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('director', models.TextField(blank=True, null=True)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'movie_actor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'movie_genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieWriter',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'movie_writer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
<<<<<<< HEAD:Django_flask_project/django_docker_nginx/django_movies/movies/migrations/0001_initial.py
                ('id', models.CharField(default=uuid.UUID('c63493bd-c0b8-41aa-8df5-72776026d42e'), max_length=36, primary_key=True, serialize=False)),
=======
                ('id', models.CharField(default=uuid.UUID('1dce47a0-b6c0-4580-a880-bad8dec66bf0'), max_length=36, primary_key=True, serialize=False)),
>>>>>>> master:django_admin/django_movies/movies/migrations/0001_initial.py
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'writer',
                'managed': False,
            },
        ),
    ]
