# Generated by Django 3.1 on 2021-03-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'actor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(default='O54KWOQNM', max_length=10, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('director', models.TextField(blank=True, null=True)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'movie_actor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'movie_genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieWriter',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'movie_writer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.CharField(default='PH164QFHJFNCDY55OFX4Y9FL135VZB0I5MNSRMIY', editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'writer',
                'managed': False,
            },
        ),
    ]
